
##### Checks run at pull request #####
##### Checks run at pull request #####
# Check quiz formatting
check-quizzes: false
quiz_error_min: 0
# Check that urls in the content are not broken
url-checker: true
url_error_min: 0
# Spell check Rmds and quizzes
spell-check: true
spell_error_min: 0

render-preview: yes

# Style any R code
style-code: yes
# Test build the docker image if any docker-relevant files have been changed
# Should URLs be tested periodically?
url-check-periodically: yes
# Would you like a readability report on your markdowns?
readability-report: yes

# What docker image should be used for rendering?
# The default is jhudsl/base_ottr:main
rendering-docker-image: 'jhudsl/base_ottr:main'
