---
title: "**Modules**"
output:
  html_document
---

## Short Modules

These materials are under 1 hour.

- [All of Us: Understanding Ethics](module/AOU_ethics.html)

## Lab-Period Modules

These modules are intended to fill a lab period, about 1.5 - 3 hours.

- [Database Detectives: Exploring Public Genomic Databases](module/database_detectives.html)

- [Family Markers: Using Multiply-Affected Families to Identify Risk Genes](module/family_markers.html)

- [Genomic Medicine: Polygenic Risk Score Calculation](module/genomic_med_prs.html)

- [Population Genetics: Koi Pond Simulation](module/pop_gen_hwe.html)


## Research Modules

These modules can be run as part of a miniCURE with the C-MOOR project or as a single, standalone lab activity.

- [Differential Expression and the Mouse Gut-Brain Axis](module/mouse_gutbrain_de.html)


## Other Modules

These modules are not strictly part of GEMs, but were created by our group and others.

- [Exam Physiology: Wearable Data and Stress](module/exam_phys.html)

