---
title: "Database Detectives: Exploring Public Genomic Databases"
format:
    html: default
---

## Overview

This activity guides students through using publicly-available genomics databases. Students start with four _Drosophila_ genes and learn how to find information about these genes, as well as information about homologous genes in mice, zebrafish, and humans. Finally, they use human disease databases to identify the human health consequences of mutations to the _Drosophila_ homologs.

This activity is loosely based on the game Clue. Students need to match four _Drosophila_ genes to the correct experimental data and background research.

**Duration:** 1-3 hours ([help us improve this estimate!](https://forms.gle/jPppG3dSnEQneDEZA))

## Learning Objectives

1. Explore commonly-used public genomic databases to become familiar with the biological information on them.

2. Identify genomic information for four different _Drosophila_ genes.

3. Compare how gene location and expression differs between species for homologous genes.

4. Determine the associations between _Drosophila_ gene homologs and human diseases. 

## Prerequisites

<!-- Example from AOU: -->
<!-- Students will benefit from some awareness of genetically-based medical conditions and ethics in genomics. We suggest this activity could accompany lectures that discuss these topics. These ethics-related questions can also be added on to any activity that leverages the [All of Us Data Browser](https://databrowser.researchallofus.org/). -->

## Evaluation

GEMs is an NIH-funded program. Part of our mission is understanding the impact of our materials. Please take the time to review our program as an instructor after this activity. We also appreciate you distributing our survey to students before and after they participate in GEMs content.

::: {.callout-tip}
## Help us improve!

[Instructor survey](https://forms.gle/jPppG3dSnEQneDEZA)

[Student pre-activity survey](https://genomicseducation.shinyapps.io/student_pre_survey/)

[Student post-activity survey](https://genomicseducation.shinyapps.io/student_post_survey/)
:::

You can view our IRB approval [here](https://drive.google.com/file/d/16Wx2CxDsmojfWacb2S1SHbYdI3kqBzFX/view?usp=sharing). Feel free to contact the GEMs team with any questions (gems **at** fredhutch **dot** org).

## Materials

### Student Activity

You can use this module in several formats. Feel free to adapt to your needs!

-   [Web page](https://genomicseducation.org/module/database_detectives_student_guide.html)
-   [Word (docx)](https://github.com/fhdsl/GEMs/raw/main/docs/docx/module/database_detectives_student_guide.docx)
-   [Google Doc](https://docs.google.com/document/d/1mlyqdhbFCfYPEdiFKX9KH2FCy34EL8Eg/edit?usp=sharing&ouid=101727846555185296348&rtpof=true&sd=true) 

Students will need a device that accesses the internet.

::: callout-warning
## This content contains URLs

We suggest confirming links are still active prior to running this activity.

Students will use these websites: [_FlyBase_](https://flybase.org/), [_Mouse Genome Informatics_](https://informatics.jax.org/), [_ZFIN (Zebrafish Information Network _](https://zfin.org/), [_GeneCards_](https://www.genecards.org/), [_OMIM_](https://omim.org/), and [_MalaCards_](https://www.malacards.org/)

### Instructor Materials

A Google Slides presentation is available for borrowing images [here](https://docs.google.com/presentation/d/1fy3FwkSLETnRUdf8huddq2n4qcb6eOyzwVg05dbudII/edit?slide=id.g2c8182c8825_0_50#slide=id.g2c8182c8825_0_50).

An answer key is available [here](https://docs.google.com/document/d/1QLoxy045YQydpZxQfaDCVLSRSi4fU00ceLBDNblAdsA/edit?tab=t.0). Please message Ava Hoffman (ahoffma2 at fredhutch dot org) to get access.

## Scientific Topics

In addition to working with public genomic databases, students are exposed to the following concepts:

- Curated Databases: databases where information is screened, validated, and organized by experts to ensure the data are accurate and reliable. Information from these databases is typically standardized and organized in a consistent way so it is easily accessible and searchable.

- Homologs and Orthologs: genes or proteins across species that are similar to each other due to having a common evolutionary origin. An ortholog is a special type of homolog, in which both genes _also_ have similar functions within different species.

- Model Organisms: species used by researchers to study specific biological processes and diseases in an effort to understand how how the processes and diseases work in humans.

- Gene Ontology: a bioinformatics initiative focused on standardizing the vocabulary and annotations researchers use to describe genes, proteins, and data about gene and protein function.

- Genome Assembly: a version of the genome map.

## Outline

- Part 1: Using FlyBase 

- Part 2: Identifying Homologs; Using Mouse Genome Informations, ZFIN, and GeneCards

- Part 3: Using OMIM and MalaCards

- Part 4: Solving the Data Mystery
