---
title: "DNA Barcoding"
date: last-modified
output:
  html_document
---


## Overview

This activity explores forensic uses of DNA barcoding and DNA reference datasets. In the prework, students will read about two real-life cases using DNA barcoding and consider the legal and biological consequences. In the lab module, students will walk through using online genomic reference databases and interpret their results within the framework of a forensic case study.

Prework can be run as a stand-alone activity.

**Duration:** 

- Prework: Approximately 30 minutes

- Lab: Approximately 1 hour ([help us improve this estimate!](https://forms.gle/pgvLDMChG19pGjCq7))

## Learning Objectives

1.  Consider the legal and biological consequences of using DNA barcoding as part of forensic investigations.

2.  Use online tools to compare sequence in fasta format to DNA barcoding reference databases.

3.  Explore species identification via DNA barcoding.

4.  Interpret DNA barcoding results within the framework of a forensic DNA investigation.

## Prerequisites

Students will benefit from a basic understanding of genome organization and taxonomic classification, as well as some awareness of PCR and genomic sequencing methods.  We suggest this activity could accompany lectures that discuss the genome or PCR methods.

## Evaluation

GEMs is an NIH-funded program. Part of our mission is understanding the impact of our materials. Please take the time to review our program as an instructor after this activity. We also appreciate you distributing our survey to students before and after they participate in GEMs content.

::: {.callout-tip}
## Help us improve!

[Instructor survey](https://forms.gle/pgvLDMChG19pGjCq7)

[Student pre-activity survey](https://genomicseducation.shinyapps.io/student_pre_survey/)

[Student post-activity survey](https://genomicseducation.shinyapps.io/student_post_survey/)
:::

You can view our IRB approval [here](https://drive.google.com/file/d/16Wx2CxDsmojfWacb2S1SHbYdI3kqBzFX/view?usp=sharing). Feel free to contact the GEMs team with any questions (gems **at** fredhutch **dot** org).

## Materials

### Student Activity

You can use this module in several formats. Feel free to adapt to your needs!

*Prework*

-   [Web page](https://genomicseducation.org/module/dna_barcoding_student_guide.html)
-   [Word (docx)](https://github.com/fhdsl/GEMs/raw/main/docs/docx/module/dna_forensics_student_guide.docx)
-   [Google Doc](https://docs.google.com/document/d/15oZa2TNwvOFMxOf8mxBbP_P-TqDPpzXq/edit?usp=sharing&ouid=101727846555185296348&rtpof=true&sd=true)

For the prework, students do not need any additional materials.

*Lab*

-   [Web page](https://genomicseducation.org/module/dna_barcoding_student_guide.html)
-   [Word (docx)](https://github.com/fhdsl/GEMs/raw/main/docs/docx/module/dna_barcoding_student_guide.docx)
-   [Google Doc](https://docs.google.com/document/d/1oALRkxlSXo0wBMgBgiOV73c_k_4SZYtL/edit?usp=sharing&ouid=101727846555185296348&rtpof=true&sd=true)

For the lab, students will need: 

- A device that accesses the internet. 
- Access to the BOLD website: <https://id.boldsystems.org/>. 
- Access to BLASTn on the NCBI website: <https://blast.ncbi.nlm.nih.gov/Blast.cgi>
- Ability to download toy data hosted at: <https://genomicseducation.org/data/barcoding_devils_claw_rbcL.fasta>

### Instructor Materials

A Google Slides presentation is available for borrowing images [here](https://docs.google.com/presentation/d/1intNjOu2eeZLBrZ2sW_BOa6acI1ZEtrjbyrazuQiawQ/edit?usp=sharing).

## Scientific Topics

Students will gain exposure to the following:

-   DNA Barcoding: a molecular biology method that identifies the species of an organism using a short, standardized section of its DNA. The DNA section used for barcoding depends on the species being barcoded.

-   Curated Databases: databases where information is screened, validated, and organized by experts to ensure the data are accurate and reliable. Information from these databases is typically standardized and organized in a consistent way so it is easily accessible and searchable.

-   Species Identification: the process of matching an individual organism to a known scientific name, or to a known taxonomic group (like family or genus)

-   Relevant laws around herbal supplements in the USA and wildlife smuggling in Brazil

## Outline


-   Part 1: Prework (30 minutes)

-   Part 2: What organism do your samples come from? (30 minutes)

-   Part 3: Verify sample identification (30 minutes)

