---
title: "DNA Barcoding and Forensics"
date: last-modified
bibliography: ../book.bib
csl: ../resources/ieee-with-url.csl
format:
    html: default
---


::: {.callout-note}
## Check Your Knowledge

1. In our example, what are some reasons for the mismatch between the expected species (_Harpagophytum procumbens_) and the species identity suggested by BOLD (_Harpagophytum zeyheri_)?

2. _Answer the following questions based on your case file samples._ According to your BOLD search, what is the species identity of the each sample in the case study you chose? What are the common names of these species?

3. What is the percent identity value for the top result of each search?

4. Do these species identities match the putative identity of each sample?
:::

::: {.callout-note}
## Check Your Knowledge

5. Why do you think we got matches to both _Harpagophytum procumbens_ and _Harpagophytum zeyheri_ for our sample?

6. _Answer the following questions based on your case file samples._ According to your GenBank search, what is the species identity of your three samples? What are the common names of these species?

7. What is the percent identity value for the top result of each search?

8. Do the species identities from the GenBank search match the species identities from the BOLD search?

9. Answer the question that matches the case file you chose.

__Herbal Medicine Investigation__ Do you think the herbal medicine manufacturers are being truthful in their advertising? If not, would you recommend any regulatory action against them? 

__Suspected Parrot Smuggling__ Should the man who was arrested at the airport be prosecuted for parrot smuggling? If so, should he face additional penalties (for attempting to smuggle endangered or migratory species)?
:::

