---
title: "DNA Forensics"
date: last-modified
output:
  html_document
---


## Overview

This activity explores forensic uses of DNA barcoding. Students will read about two real-life cases using DNA barcoding and consider the legal and biological consequences.

**Duration:** Approximately 30 minutes ([help us improve this estimate!](https://forms.gle/pgvLDMChG19pGjCq7))

## Learning Objectives

1. Understand how DNA barcoding is used in forensics. 

2. Consider the legal and biological consequences of using DNA barcoding as part of forensic investigations.


## Prerequisites

Students will benefit from a basic understanding of genome organization and taxonomic classification, as well as some awareness of PCR and genomic sequencing methods.  We suggest this activity could accompany lectures that discuss the genome or PCR methods.

## Evaluation

GEMs is an NIH-funded program. Part of our mission is understanding the impact of our materials. Please take the time to review our program as an instructor after this activity. We also appreciate you distributing our survey to students before and after they participate in GEMs content.

::: {.callout-tip}
## Help us improve!

[Instructor survey](https://forms.gle/pgvLDMChG19pGjCq7)

[Student pre-activity survey](https://genomicseducation.shinyapps.io/student_pre_survey/)

[Student post-activity survey](https://genomicseducation.shinyapps.io/student_post_survey/)
:::

You can view our IRB approval [here](https://drive.google.com/file/d/16Wx2CxDsmojfWacb2S1SHbYdI3kqBzFX/view?usp=sharing). Feel free to contact the GEMs team with any questions (gems **at** fredhutch **dot** org).

## Materials

### Student Activity

You can use this module in several formats. Feel free to adapt to your needs!

-   [Web page](https://genomicseducation.org/module/dna_forensics_student_guide.html)
-   [Word (docx)](https://github.com/fhdsl/GEMs/raw/main/docs/docx/module/dna_forensics_student_guide.docx)
-   [Google Doc](https://docs.google.com/document/d/15oZa2TNwvOFMxOf8mxBbP_P-TqDPpzXq/edit?usp=sharing&ouid=101727846555185296348&rtpof=true&sd=true)

Students do not need any outside material.

### Instructor Materials

This activity can be used as the prework for the [DNA Barcoding activity](https://genomicseducation.org/module/dna_barcoding.html)

A Google Slides presentation is available for borrowing images [here](https://docs.google.com/presentation/d/1intNjOu2eeZLBrZ2sW_BOa6acI1ZEtrjbyrazuQiawQ/edit?usp=sharing).

An answer key is available [here](https://docs.google.com/document/d/1dkVhglpXy3oDdWNTZQkdfg8nBLvnV3jkxWNtWnyoL5E/edit?usp=sharing). Please message Ava Hoffman (ahoffma2 at fredhutch dot org) to get access.

## Scientific Topics

Students will gain exposure to the following:

-   DNA Barcoding: a molecular biology method that identifies the species of an organism using a short, standardized section of its DNA. The DNA section used for barcoding depends on the species being barcoded.

-   Species Identification: the process of matching an individual organism to a known scientific name, or to a known taxonomic group (like family or genus)

-   Relevant laws around herbal supplements in the USA and wildlife smuggling in Brazil

## Outline

-   Part 1: Student reading and reflection (20 minutes)

-   Part 2: Class discussion (10 minutes)

