---
title: "**DNA Barcoding and Forensics_Student Guide**"
date: "`r format(Sys.time(), '%B %d, %Y')`"
bibliography: ../book.bib
csl: ../resources/ieee-with-url.csl
format:
    html: default
---

This activity explores forensic uses of DNA barcoding and DNA reference datasets. You will work with real data from several forensic investigations in order to identify species based on a small fragment of DNA.

## Part 1

In Part 1, we'll go over some background context for this activity. Then, you'll choose which case file you want to investigate.

### What is DNA barcoding?

**DNA barcoding** is a technique that involves sequencing a small piece of DNA in order to determine an organism's species identity. The **DNA barcode** is a short (400-800 bp in length) section of the genome that is highly variable and can be used to reliably distinguish one species from another. Although the gold standard for species identification is typically based on an individual's appearance, or morphology, this method isn't always possible in forensic investigations. For example, an investigator may be asked to identify only a small part of an organism, or be given a sample of plant matter that has been partly digested. DNA barcoding can provide identity when morphology fails.

<!-- add references! -->

DNA barcoding is only as accurate as the reference database you use... 

### What makes a good DNA barcoding region?

Sometimes the DNA barcode can't perfectly identify to species....

::: callout-tip

You may have heard of a technique called DNA fingerprinting. While similar to DNA barcoding, there are several important differences between the two techniques. 

**Region of DNA**: The DNA barcoding technique amplifies a single, highly variable region of DNA that is 400-800 base pairs long. DNA fingerprinting, on the other hand, amplifies multiple DNA regions called _variable number tandem repeats_, or VNTRs. These regions are 10-100 base pairs in length. There are many VNTR regions scattered throughout the genome. It is common to examine at least 13 different VNTR regions in a DNA fingerprinting analysis.

**Level of identification**: DNA barcoding is used to identify the species of a sample, while DNA fingerprinting identifies an individual organism. The larger number of shorter variable DNA regions allows researchers to be more precise when determining the individual a sample comes from.

:::

## Case Study: Identifying ingredients in over-the-counter herbal supplements

In 2015, the New York Attorney General temporarily halted the sale of store-brand herbal supplements from GNC, Target, Walgreens and Walmart after an investigation revealed many of these supplements did not contain any quantity of the herbs on their labels. This investigation was prompted by a 2013 New York Times article entitled "Herbal Supplements Are Not What They Seem" and reviewed research by a group of Canadian scientists that used DNA barcoding to examine whether the ingredients on the labels of herbal supplements matched the ingredients inside the capsules. The NY AG and the companies reached an agreement to resume sales, with the companies promising to implement reforms and prominently announce in stores and on its website if a supplement product was derived from whole herbs or extracts.

In 2018, inspired by these events and other research suggesting ingredient mismatch was still common, two researchers and three high schoolers from the Urban Barcode Research Program published a study examining whether herbal medicinal products bought online contained what their labels said they contained. The Urban Barcode Research Program is a science education initiative based in New York City that connects high school students with researchers to do biodiversity studies in the city. These students were particularly interested in this research question because they belonged to communities where herbal supplements and herbal medicine were commonly used.

This type of forensic DNA activity is a type of _pharmacovigilance_ research.

You can read more about the students' study here.
>Molina J, Sherpa C, Ng J, Sonam T, Stuhr N. DNA Barcoding of Online Herbal Supplements: Crowd-sourcing Pharmacovigilance in High School. Open Life Sci. 2018 Apr 6;13:48-55. doi: 10.1515/biol-2018-0007. PMID: 33817067; PMCID: PMC7874675.

::: callout.tip

In the United States, pharmaceuticals are regulated by the FDA under the authority of the Federal Food, Drug, and Cosmetic Act (FFDC). This law gives the US government the authority to oversee the safety of food, pharmaceuticals, medical devices, and cosmetics. In particular, the FFDC requires that food, pharmaceuticals, medical devices, and cosmetics be clearly and accurately labeled with their ingredients.

However, herbal supplements and herbal medicinal products are not regulated in the same way as pharmaceuticals. These products are considered dietary supplements, which are regulated under the Dietary Supplement Health and Education Act. Products that fall under the purview of the Dietary Supplement Health and Education Act have much looser regulations around labeling, testing, and effectiveness. Although companies are required to verify that their dietary supplements are safe and accurately labeled, the FDA generally relies on an honor system.
:::

Pharmacovigilance is only one use of DNA barcoding in forensics! Expand each case file to learn more about how DNA fingerprinting has been used in forensic investigations.

::: {.callout-caution collapse="true"}
# Case File: Suspected Parrot Smuggling

In Brazil, wildlife is considered the property of the Brazilian State and the commercial trade of wild animals is strictly controlled (Fauna Protection Law; law no. 5197/1967). Anyone who catches, transports, keeps captive, or sells wild animals _without proper authorization_ can face fines and up to 6-12 months of prison time. These penalties increase if the wild animal is endangered or belongs to a migratory species, among other things (Environmental Crimes Law; law no. 9605/1998).

In their 2015 paper "DNA Barcoding Identifies Illegal Parrot Trade", Gonçalves et al. detail a forensic investigation of a potential animal smuggling incident at an airport in Brazil. This is their brief overview of the case:

> Here we report a case from 2003 of a man who was arrested at Recife International Airport in Brazil carrying 58 unhatched avian eggs and intending to fly to Europe. The eggs were packed around his abdomen to keep them alive during the trip. The police were already investigating him, and during this trip to Brazil he visited various states where he could have acquired the eggs. When arrested, he claimed that they were quail eggs, but their external morphology did not support his claim. The embryos never hatched; thus, it was not possible to identify them based on their morphology. However, the external morphology of the eggs and embryos suggested that they were from parrots.

This is an excellent situation for DNA barcoding! Many bird eggs look alike and can't easily be identified to genus level, let alone species level. Additionally, 30% of parrot species are endangered. It is important to know the parrot species in order to properly charge this man under Brazilian law.

You can read more about the study here.
>Gonçalves PF, Oliveira-Marques AR, Matsumoto TE, Miyaki CY. DNA Barcoding Identifies Illegal Parrot Trade. J Hered. 2015;106 Suppl 1:560-4. doi: 10.1093/jhered/esv035. PMID: 26245790.

## What barcoding gene do they use for birds?

:::


## Part 2: What organism do your samples come from?

## Part 3: Verify sample identification

## Part 4: Are the samples what we expect?

parrots: do the eggs belong to endangered or migratory species?

fish: are the fish endangered?

plants: are the plants toxic?