---
title: "Exam Physiology: Wearable Data"
output:
  html_document
---

```{r, fig.align='center', echo = FALSE, fig.alt= "A wrist showing a wearable device and inset, several students taking an exam.", out.width = '90%'}
ottrpal::include_slide("https://docs.google.com/presentation/d/1PxVdyZui3Hpn883FSzZRgqFTJnbv54-w0-uuPUNJDHI/edit?slide=id.g3c8730600da_1_25#slide=id.g3c8730600da_1_25")
```

## Overview

This module introduces data analysis of physiology data. Students work with real physiological data collected from college students wearing stress-monitoring devices during exams. The data includes skin conductance (EDA), heart rate, and skin temperature measurements. The eventual goal of the researchers was to predict students' grades from stress measurements.

Students will use Posit Cloud (an online version of R programming language and R Studio) to load and explore the data, calculate correlations between variables, visualize individual student data, compare two students side by side, and finally explore other students and form hypotheses about how physiological data is related to actual grades.

**Duration:** 1.5 - 2.5 hours

## Learning Objectives

1.  Work with data related to functional cardiovascular activity, temperature homeostasis, and stress

2.  Experiment with technical R skills

3.  Think scientifically (interpret data, form hypotheses)

3.  Understand correlation and causation

## Prerequisites

Students will benefit from being enrolled in an anatomy and physiology course. They do not need to have programming experience (code is largely copied and pasted).

## Evaluation

GEMs is an NIH-funded program. Part of our mission is understanding the impact of our materials. Please take the time to review our program as an instructor after this activity. This activity's evaluation is a bit different, as it's not part of the core GEMs curriculum.

::: callout-tip
## Help Us Improve!

[Instructor experience survey](https://forms.gle/vquSK16nrbdmjFF28)
:::

You can view our IRB approval [here](https://drive.google.com/file/d/16Wx2CxDsmojfWacb2S1SHbYdI3kqBzFX/view?usp=sharing). Feel free to contact the GEMs team with any questions (gems **at** fredhutch **dot** org).

## Materials

### Student Activity

You can use this module in several formats. Feel free to adapt to your needs!

-   [Web page](https://genomicseducation.org/module/exam_phys_student_guide.html)
-   [Quarto (qmd)](https://github.com/fhdsl/GEMs/blob/main/module/exam_phys_student_guide.qmd)
-   [Word (docx)](https://github.com/fhdsl/GEMs/raw/main/docs/docx/module/exam_phys_student_guide.docx)
-   [Google Doc](https://docs.google.com/document/d/18vj-yEwVlu-jxE_rBuKBOlS9TOPDiHvI/edit?usp=sharing&ouid=116032995747974603894&rtpof=true&sd=true)

Students will need a device that accesses the internet.

::: callout-warning
## This content contains URLs

We suggest confirming links are still active prior to running this activity:

* <https://posit.cloud/plans/free>
* <https://genomicseducation.org/data/phys_data.csv>
:::


### Instructor Materials

An answer key is available [here](https://docs.google.com/document/d/13sftVTyWNY7Rya1D39doqlBG2_yqtC0o/edit?usp=sharing&ouid=116032995747974603894&rtpof=true&sd=true). Please message Ava Hoffman (ahoffma2 at fredhutch dot org) to get access.
