---
title: "Exam Physiology: Wearable Data"
date: last-modified
bibliography: ../book.bib
csl: ../resources/ieee-with-url.csl
format:
    html: default
---


::: callout-note
## Check Your Knowledge

1.  What variables were the researchers trying to measure?

2.  True or False: High Electrodermal activity (EDA) means the person being measured might be stressed.
:::

::: callout-note
## Check Your Knowledge

1.  Why might we want to install add-on packages in R?

2.  How can we confirm that our data loaded correctly? Take a screenshot and point to your evidence.

3.  Looking at the `timestamp` column, how often are measurements being collected?

4.  How many rows of data, or observations, does this data have? Hint: look at the Environment Pane (top right) and see how many `obs.` you have.
:::

::: callout-note
## Check Your Knowledge

1.  Run `count(phys_data, test, studentID) %>% print(n=30)` to see student and test combinations. How many observations does student `S8` have for the Final? Take a screenshot showing this number.

2.  Which student has the lowest number of observations for the Final?
:::

::: callout-note
## Check Your Knowledge

1.  Sort the `hr` column. What is the greatest heart rate observed? Which student was this? Take a screenshot of your evidence.

2.  Which student had the greatest eda values? Which exam was this? Take a screenshot of your evidence.
:::

::: callout-note
## Check Your Knowledge

1.  Change the code above slightly, replacing `hr` with `eda`. Run the changed code in your console. What is the correlation between the `temp` and `eda` variables? Take a screenshot of your evidence.

2.  What does the correlation value tell you about the relationship between these two variables? (E.g., as one goes up, the other does what ?)

3.  (Optional) Try changing the code again to look at the correlation value between `eda` and `hr`. Run the changed code in your console. What is the correlation between these variables, and what is the relationship? Take a screenshot of your evidence.
:::

::: callout-note
## Check Your Knowledge

1.  Change the code that creates the plots slightly, replacing `hr` with `eda`. Run the changed code in your console. Take a screenshot of your plots.

2.  Which test/exam appears to have the greatest electrodermal activity (EDA) for student `S9`?

3.  To confirm your results, calculate the mean `eda` for each test. Run the code above to calculate the means, remembering to replace `hr` with `eda`. Do the results surprise you? Take a screenshot of your results table in the console.

4.  (Optional) Try running 1-3 above with student `S8` instead of `S9`. You'll need to replace anywhere `S9` was mentioned in the code! Take a screenshot of your plots/results.
:::

::: callout-note
## Check Your Knowledge

1.  Change the code that creates the plots, replacing `hr` with `eda`. Run the changed code in your console. Take a screenshot of your plots.

2.  What conclusions can you draw about stress in these two students, based on their `EDA` measurements?

3.  (Optional) To confirm your results, compare the mean eda for each test and student (`S9` and `S8`). You can return to the code from Part 4 and re-calculate it if you need to. Do the results back up your conclusions from question 2? Take a screenshot of your results table in the console.

4.  (Optional) Try running 1-3 above with two different students. You'll need to replace anywhere `S9` or `S8` was mentioned in the code with the students of your choice. Take a screenshot of your plots/results.
:::

::: callout-note
## Going Deeper

1.  Based on your plots and information so far, do you have any ideas (hypotheses!) about how stress and grades might be related?

2.  Would looking at more data help you feel more or less comfortable with your hypotheses?

3.  Look at some of the values for `temp`. Are these realistic? Why or why not?
:::

