---
title: "Genomic Medicine: Polygenic Risk Score Calculation"
date: last-modified
bibliography: ../book.bib
csl: ../resources/ieee-with-url.csl
format:
    html: default
---


::: {.callout-note}
## Check Your Knowledge

1. When treating genetic disease, why is it important to examine multiple genes, rather than examine one gene at a time?

1. Which of these are accurate statements?  
    a. Having certain gene variants can mean increased risk of disease.  
    b. Higher PRS scores guarantee development of disease.  
    c. PRS must be based on an appropriate database of gene variants.  
    d. All variants come from protein-coding genes.  

1. Try looking up another variant at <https://www.ebi.ac.uk/gwas/variants>. Look up "rs2075650". Take a screenshot/screenshots that capture:
    a. The kind of variant is listed under "Most severe consequence"
    b. Any diseases associated with this variant?

:::

::: {.callout-note}
## Check Your Knowledge

1. Provide a screenshot of your calculated PRS and percentile.

2. Based on the PRS and percentile you calculated, will Mr. J develop prostate cancer? Why or why not? 

2. Go to the [_Conti_ (GCST011047) study page](https://www.ebi.ac.uk/gwas/studies/GCST011047) and look at the description under "Discovery ancestry label". What ancestries are included? Provide a screenshot.
    
3. How many people were used to identify these variants in the _Conti_ study? Hint: add up the cases (has cancer) and controls (no cancer) under "Discovery sample description".
:::

::: {.callout-note}
## Check Your Knowledge

1. Provide a screenshot of your calculated PRS and percentile, now with both studies.

2. Go to the [_Eeles_ (GCST000152) study page](https://www.ebi.ac.uk/gwas/studies/GCST000152) and look at the description under "Discovery ancestry label". What ancestry is included? Provide a screenshot.

3. Given that Mr. J has African ancestry, which study (_Conti_ or _Eeles_) is a more appropriate match to assess his risk?
    
4. Imagine you were helping Mr. J's providers craft a care plan. Based on Mr. J's results, would you recommend more frequent screening? Why or why not?
:::

::: {.callout-note}
## Check Your Knowledge

1. Provide a screenshot of your calculated PRS and percentile, with both studies.

2. Which study is more appropriate if Mr. B has African ancestry? European ancestry?
    
3. Would you recommend more frequent screening to Mr. B? Why or why not? How do his results compare to Mr. J's results?
:::

