---
title: "Genomic Medicine: Polygenic Risk Score Calculation"
format:
    html: default
---

```{r, fig.align='center', echo = FALSE, fig.alt= "TO ADD", out.width = '90%'}
ottrpal::include_slide("https://docs.google.com/presentation/d/1QxPej8YIbgsToOITRYKLxmGScjo0Eu5ldiKEE-lXvF0/edit?slide=id.g35f4636d8f5_0_6#slide=id.g35f4636d8f5_0_6")
```

## Overview

This activity will walk through how to use an online polygenic risk score (PRS) calculator, as well as how to interpret the outcome. Students will compare calculations using different studies, demonstrating the importance of study selection and ancestry in PRS interpretation.

**Duration:** Approximately 1.5-2 hours ([help us improve this estimate!](https://forms.gle/rYeVE9BAQ4GhhXtZ6))

## Learning Objectives

1.  Differentiate between Mendelian and polygenic traits.

2.  Explore variants and studies through an online database (EMBL-EBI).

3.  Calculate and interpret polygenic risk scores.

4.  Compare risk percentiles using studies that were conducted using cases and controls from different ancestral populations.

5.  Identify and critique scientific issues relating to society or ethics (see [GSA](https://genetics-gsa.org/education/genetics-learning-framework/) core competencies).

## Prerequisites

Students will benefit from some awareness of genetically-based medical conditions, the concept of polygenic traits, and disease risk. We suggest this activity could accompany lectures that discuss these topics.

## Evaluation

GEMs is an NIH-funded program. Part of our mission is understanding the impact of our materials. Please take the time to review our program as an instructor after this activity. We also appreciate you distributing our survey to students before and after they participate in GEMs content.

::: {.callout-tip}
## Help us improve!

[Instructor survey](https://forms.gle/rYeVE9BAQ4GhhXtZ6)

[Student pre-activity survey](https://genomicseducation.shinyapps.io/student_pre_survey/)

[Student post-activity survey](https://genomicseducation.shinyapps.io/student_post_survey/)
:::

You can view our IRB approval [here](https://drive.google.com/file/d/16Wx2CxDsmojfWacb2S1SHbYdI3kqBzFX/view?usp=sharing). Feel free to contact the GEMs team with any questions (gems **at** fredhutch **dot** org).

## Materials

### Student Activity

You can use this module in several formats. Feel free to adapt to your needs!

-   [Web page](https://genomicseducation.org/module/genomic_med_prs_student_guide.html)
-   [Quarto (qmd)](https://github.com/fhdsl/GEMs/blob/main/module/genomic_med_prs_student_guide.qmd)
-   [Word (docx)](https://github.com/fhdsl/GEMs/raw/main/docs/docx/module/genomic_med_prs_student_guide.docx)
-   [Google Doc](https://docs.google.com/document/d/1qHzUEttKBJYxmcg7bnjQBMBSF_fKeVOz/edit?usp=sharing&ouid=116032995747974603894&rtpof=true&sd=true)

Students will need: 

- A device that accesses the internet. 
- Access to this website: <https://prs.byu.edu/calculate_score.html>. Access to Microsoft Excel or Google Sheets may be helpful.
- Ability to download toy data hosted at: <https://genomicseducation.org/data/prs_ind_1.txt>

::: callout-warning
## This content contains URLs

We suggest confirming links are still active prior to running this activity. Students will use this website: <https://prs.byu.edu/calculate_score.html>.
:::

### Instructor Materials

A Google Slides presentation is available for borrowing images [here](https://docs.google.com/presentation/d/1QxPej8YIbgsToOITRYKLxmGScjo0Eu5ldiKEE-lXvF0/edit?usp=sharing).

An answer key is available [here](https://docs.google.com/document/d/1JJ0hsDxtZZU5dg3xZ7GfK2ifkETH0NaK/edit?usp=sharing&ouid=116032995747974603894&rtpof=true&sd=true). Please message Ava Hoffman (ahoffma2 at fredhutch dot org) to get access.

You might wish to review additional background on [PRS Scores](https://drive.google.com/file/d/1iIf2Ju3FQ-G6jltcZwaQ5uK8wdcifHy2/view?usp=sharing) and [Prostate Cancer](https://drive.google.com/file/d/1JRhhsvLnt3agfExkF59ay4fqExVCaYcR/view?usp=sharing).

## Scientific Topics

This activity focuses on understanding genetic risk in human disease. Students will gain exposure to the following:

- Polygenic Risk Scores (PRS): This method estimates disease risk based on the cumulative effect of many genetic variants, each contributing a small amount. Students will use an online calculator.

- Genomic Medicine: Discipline that uses genome-wide variant data to guide diagnosis and help determine treatment plans, especially for common diseases like diabetes or heart disease.

- Genomic Databases: Students will look up variants linked to disease traits in EMBL-EBI, which are used to calculate PRS.

- Ethics & Equity in Genomics: Current PRS tools are more accurate in individuals of European ancestry, which can facilitate discussion about health disparities and life saving treatment (e.g., early screening).

## Outline

-   Part 1: Background and Data (30-40 minutes)

-   Part 2: Calculating PRS Score (45 minutes)

-   Part 3: Comparing Studies for PRS (20-30 minutes)
