---
title: "Differential Expression and the Mouse Gut-Brain Axis"
bibliography: ../book.bib
csl: ../resources/ieee-with-url.csl
output:
  html_document
---

```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

## Overview

This module introduces students to differential expression analyses using the R programming language. Previous programming experience is helpful but not necessary. Students will work with real data from a mouse RNA-seq study to explore how the gut-brain axis might impact symptoms in Autism Spectrum Disorder.

This module is a companion and expansion to the C-MOOR RNA-seq miniCURE. This module adds an additional RNA-seq dataset that is suitable for an independent research project.

You can find out more about the RNA-seq miniCURE and other C-MOOR activities at the [C-MOOR website](https://www.c-moor.org/). An online guide to the miniCURE is [here](https://science.c-moor.org/miniCURE-RNA-seq/index.html).

**Duration:** Three lab periods

## Learning Objectives

1.  Explore differential expression data in mice.

2.  Identify genes that are differentially expressed in an RNA-seq dataset.

3. (Optional) Formulate and test a hypothesis about differential expression of genes as a result of the gut-brain axis.

## Materials and Setup

-   Students will need either:

    -   An internet connection for this activity as written (using Posit Cloud)
    -   A local installation of R or RStudio (with data downloaded and `tidyverse` package installed ahead of time)

-   Required R package: `tidyverse`, `ggrepel`
 
-   Data hosting:

    -   [Sample metadata](mouse_gutbrain_metadata.csv)

    -   [Gene expression count data for all control-type mice](https://genomicseducation.org/data/mouse_gutbrain_de_counts_controls.csv)
    -   [Gene expression count data for all ASD-type mice](https://genomicseducation.org/data/mouse_gutbrain_de_counts_asd.csv)
    -   [Gene expression count data for all prefrontal cortex samples](https://genomicseducation.org/data/mouse_gutbrain_de_counts_prefrontalcortex.csv)
    -   [Gene expression count data for all striatum samples](https://genomicseducation.org/data/mouse_gutbrain_de_counts_striatum.csv)

    -   [Comparing gene expression between ASD and control mice, both brain regions](https://genomicseducation.org/data/mouse_gutbrain_de_autismVcontrol.csv)
    -   [Comparing gene expression between ASD and control mice, prefrontal cortex only](https://genomicseducation.org/data/mouse_gutbrain_de_autismVcontrol_in_prefrontalcortex.csv)
     -   [Comparing gene expression between ASD and control mice, striatum only](https://genomicseducation.org/data/mouse_gutbrain_de_autismVcontrol_in_striatum.csv)
     -   [Comparing gene expression between prefrontal cortex and striatum, all mice](https://genomicseducation.org/data/mouse_gutbrain_de_tissuetype.csv)
     -   [Comparing gene expression between prefrontal cortex and striatum, only ASD mice](https://genomicseducation.org/data/mouse_gutbrain_de_tissuetype_in_ASDmice.csv)
     -   [Comparing gene expression between prefrontal cortex and striatum, only control mice](https://genomicseducation.org/data/mouse_gutbrain_de_tissuetype_in_controlmice.csv)



-   Download the R student activity as:

    -   [Web page](https://genomicseducation.org/module/mouse_gutbrain_de_miniCURE_guide.html)
    -   [Quarto (qmd)](https://github.com/fhdsl/GEMs/blob/main/module/mouse_gutbrain_de_miniCURE_guide.qmd)
    -   [Word (docx)](https://github.com/fhdsl/GEMs/raw/main/docs/docx/module/mouse_gutbrain_de_miniCURE_guide.docx)
    -   [Google Doc]() - coming soon!


-   Google Slides presentation available for borrowing images [here](https://docs.google.com/presentation/d/1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY/edit?usp=sharing).



## Scientific Topics

The activity uses data from a [published research study](https://www.cell.com/cell/fulltext/S0092-8674(19)30502-1) "Human Gut Microbiota from Autism Spectrum Disorder Induces Behavioral Deficits in Mice" [@sharon2019]. Students will gain exposure to the following:

-   Differential expression: the process where different cells within an organism, even those with the same DNA, express different genes, with some genes being expressed or "turned on", while others are "turned off"

-   Gut-brain axis: the proposed connection between the gut microbiome and gene expression in the brain

-   Autism Spectrum Disorder: a neurological disorder that affects behavioral and social interactions

-   Neurodevelopmental disorders: disorders that are the result of altered brain development

-   Neurodegenerative disorders: disorders that that occur when brain structures and systems experience degradation

-   Prefrontal cortex: the part of the brain that is primarily in charge of decision making, reasoning, personality, maintaining social appropriateness, and other complex behaviors that fall under the umbrella of executive functions

-   Striatum: the part of the brain involved in motor control and cognitive tasks like reward processing, decision-making, and social interactions



## Outline for RNA-seq miniCURE Extension 

-   Background and Setup

-   Developing a Hypothesis; Identifying Genes of Interest

-   Exploring Gene Expression Data

-   Analyzing Differential Expression Data
