---
title: "Population Genetics: Fish Pond Simulator"
output:
  html_document
---

```{r, fig.align='center', echo = FALSE, fig.alt= "A pond full of koi, a single koi fish, and a data collection table from the simulation.", out.width = '90%'}
ottrpal::include_slide("https://docs.google.com/presentation/d/10EohJqU8e_A34_WxDvBKAvLnk9wMkrB_b_YRAw-0Q6I/edit?slide=id.g3c933021525_28_0#slide=id.g3c933021525_28_0")
```

## Overview

This module uses the [PopGen Fishbowl simulator](https://virtualbiologylab.org/ModelsHTML5/PopGenFishbowl/PopGenFishbowl.html) to model natural selection and genetic drift, as well as explore whether populations are at Hardy-Weinberg equilibrium.

**Duration:** 1 - 2 hours

## Learning Objectives

1.  Determine if a population is in Hardy-Weinberg equilibrium

2.  Compare and contrast natural selection and genetic drift

3. Predict outcomes of interactions between genotypes and environmental pressures

## Prerequisites

Students will benefit from some awareness of basic evolutionary theory, particularly Mendelian inheritance, as well as the concepts of phenotypes, genotypes, and the relationship between the two. Students should also understand the concepts of genetic drift and natural selection.

## Evaluation

GEMs is an NIH-funded program. Part of our mission is understanding the impact of our materials. Please take the time to review our program as an instructor after this activity. We also appreciate you distributing our survey to students before and after they participate in GEMs content.

::: callout-tip
## Help Us Improve!

[Instructor experience survey](https://forms.gle/Gjxn8t6JTmNrkoKu8)

[Student pre-activity survey](https://genomicseducation.shinyapps.io/student_pre_survey/)

[Student post-activity survey](https://genomicseducation.shinyapps.io/student_post_survey/)
:::

You can view our IRB approval [here](https://drive.google.com/file/d/16Wx2CxDsmojfWacb2S1SHbYdI3kqBzFX/view?usp=sharing). Feel free to contact the GEMs team with any questions (gems **at** fredhutch **dot** org).

## Materials

### Student Activity

You can use this module in several formats. Feel free to adapt to your needs!

- [Web page](https://genomicseducation.org/module/pop_gen_hwe_student_guide.html) 
- [Quarto (qmd)](https://github.com/fhdsl/GEMs/blob/main/module/pop_gen_hwe_student_guide.qmd)
- [Word (docx)](https://github.com/fhdsl/GEMs/raw/main/docs/docx/module/pop_gen_hwe_student_guide.docx) 
- [Google doc](https://docs.google.com/document/d/1Fz5AIrtasHqAgBOQei7P2b1di5YLBCwl/edit)

Students will need a device that accesses the internet. 

::: callout-warning
## This content contains URLs

We suggest confirming links are still active prior to running this activity.

In particular, students will be accessing the [PopGen Fishbowl simulator](https://virtualbiologylab.org/ModelsHTML5/PopGenFishbowl/PopGenFishbowl.html).
:::

### Instructor Materials

An answer key is available [here](https://docs.google.com/document/d/15mUV8ZTZq9CeQT7RUfyiUZT7trbh6TDdGHrIHco2yXQ/edit?usp=sharing). Please message Ava Hoffman (ahoffma2 at fredhutch dot org) to get access.

This answer key also provides guidance on areas of the activity that students may find tricky.

### Scientific Topics

### Outline

- Activity 1: Hardy-Weinberg Equilibrium 
- Activity 2: Drift 
- Activity 3: Natural Selection and Environmental Pressures 
- Bonus Activity


