{
  "hash": "c6fbfce8b0feaab5ac76f80fad65e994",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**Differential Expression and the Mouse Gut-Brain Axis**\"\nformat:\n    html: default\n---\n\n\n\n\n\nThis module provides data for an independent project exploring differential expression in RNA-seq data.\n\nThis activity will walk through differential expression analysis and use bioinformatics tools (R) to understand how gut bacteria can influence the expression of genes in the brain (the gut-brain axis). You will work with real data from a mouse RNA-seq experiment.\n\nThe basic steps of your analysis are:\n\n1.  Identify mouse genes of interest for your project.\n\n2.  Characterize the gene expression of your genes of interest in the dataset.\n\n3.  Explore differential gene expression in the control vs experimental group.\n\n## What sorts of questions can I investigate?\n\nThe data for this activity includes gene expression data from two different brain regions (striatum and prefrontal cortex) in mice. Additionally, there are two different types of mice. Some of the mice are an Autism Spectrum Disorder-type (see below for details), while others are control-type.\n\n### The Striatum, the Prefrontal Cortex, and Autism Spectrum Disorder\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g33d1434cdd1_12_0.png){fig-align='center' fig-alt='Image of the striatum in the human brain.' width=100%}\n:::\n:::\n\n\n\nThe *striatum* is part of the brain involved in motor control and cognitive tasks like reward processing, decision-making, and social interactions (often called executive functions). It lies deep within the center of the brain and is composed of both gray matter (which can be thought of as the \"processing\" part of brain tissue) and white matter (which is the brain structure involved in transporting messages); the combination of the gray and white matter give this region of the brain a striped appearance, resulting in the name \"striatum\". The striatum is involved in both reflexive movement - that is, involuntary movement that happens as an immediate response to a stimulus - and slower, planned movement like walking. In Parkinson's disease, some patients experience degeneration of parts of the striatum, resulting in spastic, uncontrollable movement.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g33d1434cdd1_12_10.png){fig-align='center' fig-alt='Image of the prefrontal cortex in the human brain.' width=100%}\n:::\n:::\n\n\n\nThe *prefrontal cortex* is the part of the brain that is primarily in charge of decision making, reasoning, personality, maintaining social appropriateness, and other complex behaviors that fall under the umbrella of executive functions. This can include planning, self-control, and working towards long-term goals. The prefrontal cortex is located in the very front of the brain, just behind your forehead. One of the most famous brain injury patients was Phineas Gage, a railroad worker who survived an iron rod through his forehead. His prefrontal cortex was destroyed in this accident, and doctors noted huge behavioral and personality changes. You can read more about his case [here](https://pmc.ncbi.nlm.nih.gov/articles/PMC1114479/).\n\n*Autism spectrum disorder (ASD)* is a neurological disorder that affects behavioral and social interactions, among other things. Although ASD can be diagnosed at any age, it's considered a neurodevelopmental disorder because symptoms usually show up within the first two years of life. Individuals diagnosed with ASD can experience a wide range of symptoms, including differences in social behaviors and communication styles, as well as intellectual disabilities and physical issues like sensory sensitivities or gastrointestinal problems.\n\nThe **gut-brain axis** is the term used for the proposed connection between the gut microbiome and the brain. In recent years, studies have identified links between immune-related neurological symptoms and the presence of intestinal inflammation. There are around 100 million neurons in the human gut, and around 70% of the serotonin (an important neurotransmitter) in the human body is made in the gut. One proposed mechanism for how the gut-brain axis works is that inflamed intestinal tissue triggers the synthesis of cytokines and other proteins involved in the immune response; these proteins may attack nervous system cells. A possible link between the gut microbiome and increased symptom severity is actively being studied for Major Depressive Disorder, Autism Spectrum Disorder, fibromyalgia, migraines, Parkinson’s disease, Alzheimer’s disease, and more.\n\n::: callout-tip\n# Deciding on your research question\n\nBefore you start working with the dataset, you should decide what you want to explore.\n\n1) Is there a gene or set of genes linked to a biological process you're particularly interested in? This could include things like \"cytokines\", \"anti-inflammatory genes\", \"genes involved in building neurons\", or any biological process you find interesting!\n\n2) Is there a disease or disorder you'd like to focus on? You can explore known risk genes for this disorder (or genes that are protective against this disorder). You don't have to limit yourself to Autism Spectrum Disorder, either; there are many disorders that have a shared genetic and biological basis!\n\n3) Are you curious about the standard \"housekeeping\" genes that are broadly expressed across cell types and involved in common biological processes, like DNA replication, metabolism, and cell cycle regulation? These processes are vitally important for proper cellular function, so disruption in them can cause problems for the organism.\n\nOnce you've picked a disorder or cellular process that interests you, start looking up research papers to find genes! You can use sites like PubMed and Google Scholar to look up studies. Skim through at least 4-5 different papers that contain some type of gene name or a biological process. **DO NOT GET TOO LOST INTO THE PAPERS!** Make sure you skim through them for important information, but be willing to set a paper aside if you're struggling to find what you need.\n:::\n\n### The original study\n\nThe original study, *Human Gut Microbiota from Autism Spectrum Disorder Induces Behavioral Deficits in Mice*, was published in 2019. Gut microbiota are known to be different between individuals with ASD and individuals who are considered typically-developing. Additionally, some individuals with ASD also experience gastrointestinal symptoms, and their gut microbiota show the greatest difference when compared to the gut microbiota of typically-developing individuals. Some researchers have proposed that gut bacteria can influence some of the symptoms of ASD. The relationship between the intestinal microbiome and the development and function of the human brain is known as the *gut-brain axis.*\n\nIn this study, researchers explored whether they could induce ASD-like behaviors in mice by changing their gut microbiome. Mice in this experiment received fecal transplants. Some mice received transplants from humans who have been diagnosed with ASD, while other mice received transplants from humans who did not have any diagnosis (control). This allowed researchers to control the composition of the gut microbiome in each mouse. They discovered that colonization with gut microbiota was enough to induce ASD-like behaviors in the mice. They also let the mice breed and collected gene expression data from the brains of their offspring to explore whether changing the gut microbiota could result in changed gene expression. In particular, they discovered that the offspring of mice who received stool from ASD donors showed different gene splicing and expression profiles of certain ASD-relevant genes.\n\n::: callout-note\nIt is important to note that researchers are **not** suggesting that ASD is entirely induced by gut bacteria. There is a strong genetic component to ASD. Scientists have known for years that there are **both genetic and environmental components** to the development or severity of **some** ASD symptoms. This research explores one possible environmental component.\n:::\n\nYou can read the original research paper [here](https://www.cell.com/cell/fulltext/S0092-8674(19)30502-1).\n\n### The mouse as a model organism\n\nThe mouse is the most commonly-used model organism in laboratory work. In fact, mice and rats make up 95% of the lab animal population, and more than 80% of the research that has been awarded the Nobel Prize for Medicine was done at least in part with mouse models (https://www.cshl.edu/of-mice-and-model-organisms/, https://fbresearch.org/medical-advances/nobel-prizes).\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g33d1434cdd1_12_19.png){fig-align='center' fig-alt='The mouse is the most commonly-used model organism in labs.' width=100%}\n:::\n:::\n\n\n\nSo what makes mice such good model organisms for biomedical research? Well, first, they're economical and relatively easy to keep. Since mice are small, they don't require a huge amount of space or food. They also have fast reproductive cycles, so researchers can study multiple generations within only a few years. Most importantly, though, mice and humans are both mammals and have about 85% of their protein-coding genome in common. As a result, mouse physiology is quite similar to human physiology. The mouse circulatory, reproductive, digestive, hormonal, and nervous systems are frequently used as models to study how humans grow, age, and develop chronic diseases. They are particularly important model organisms for cancer research and neuroscience.\n\nYou can find additional information about how the mouse is used in research [here!](https://www.google.com/url?q=https://www.informatics.jax.org/mgihome/other/homepage_IntroMouse.shtml)\n\n## Identifying genes of interest with the Mouse Genome Informatics database\n\nThe [Mouse Genome Informatics](https://www.informatics.jax.org/genes.shtml) database that tracks mouse genes and expression data. A full introduction to everything available through the MGI can be found [here](https://www.informatics.jax.org/mgihome/other/homepage_usingMGI.shtml). We'll reproduce some of it below.\n\n### Mouse gene IDs\n\nIn this dataset, genes are identified using their Ensembl Gene ID code. Every gene has an ID that looks something like this:\n\n> ENSMUSG00000000001\n\n**ENS** stands for \"Ensembl\". Ensembl is a [genome database project](https://ensemblgenomes.org/) managed by the European Bioinformatics Institute. It's one of several databases like this. Others include NIH's National Center for Biotechnology Information (NCBI; the organization that manages GenBank and PubMed) and the University of California, Santa Cruz (UCSC) Genome Browser. When a gene code starts with \"ENS\", it means you should look up the gene code in the Ensembl database.\n\n**MUS** stands for \"Mus\", which is the genus for the mouse.\n\n**G** stands for \"Gene\". When you see \"G\" in the ID name, you know you are working with a gene. There are also codes for transcripts (\"T\"), exons (\"E\"), and proteins (\"P\").\n\n**00000000001** is the numerical code associated with the gene.\n\n::: callout-tip\n# Picking your genes\n\nThe MGI allows you to look up information about genes you're interested in but don't know much about. This is particularly helpful if you are interested in genes that were identified in other research organisms or in previous studies. You could also start by looking up a human disease and associated human risk genes, then identify the homologous mouse genes.\n\nMake sure you are recording the name and gene ID for the mouse! Gene names are often similar between mice and humans, but the gene IDs will be very different. If you don't use the correct gene ID when exploring this dataset, you won't get very far.\n:::\n\n### Looking up details on a mouse gene when you have the Ensembl gene ID\n\nTo look up information on a particular gene of interest, choose the \"Genes\" button.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g357f7ed062e_9_0.png){fig-align='center' fig-alt='To look up information on a particular gene of interest, choose the “Genes” button.' width=100%}\n:::\n:::\n\n\n\nNext, type the gene ID into the \"Search\" bar up top. We'll look up \"ENSMUSG00000079516\".\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g3412c9eee7c_0_1.png){fig-align='center' fig-alt='Type the gene ID into the “Search” bar up top.' width=100%}\n:::\n:::\n\n\n\nAfter you type the gene ID into the Search bar and hit enter, you should see a new page with basic information about the gene. Click on the gene symbol (in this example, Reg3a) to get more detailed information.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g346083d4dc0_0_0.png){fig-align='center' fig-alt='Click on the gene symbol (in this example, Reg3a) to get more detailed information.' width=100%}\n:::\n:::\n\n\n\n::: callout-note\nYou might come across some unexpected terms when you search the MGI for your gene ID. In addition to genes, Ensembl gene IDs are also given to \"pseudogenes\", \"putative genes\", and \"lncRNA\".\n\n**pseudogene**: This is a stretch of DNA that looks like a gene but doesn't actually code for any protein products. It's essentially a copy of a gene that contains mutations that prevent translation into a protein product. The mutations can include partial deletions, missing promoters, missing start codons, premature stop codons, frameshift mutations, or missing introns. Any of these are enough to result in a pseudogene.\n\n**putative gene**: This is a DNA segment that is believed to be a gene, but its function and protein product has not been confirmed. They are frequently identified based on the presence of an Open Reading Frame. Putative genes are not given names until they become confirmed genes.\n\n**lncRNA**: This stands for \"long non-coding RNA\". lncRNA is a type of RNA molecule that is transcribed from DNA but does not code for proteins. These RNA molecules are at least 200-500 nucleotides long and play roles in various biological processes, like gene regulation.\n:::\n\nOn the new page that you open, details about the gene are organized into familiar categories. Down the left-hand side of the page, you will see sections about the chromosomal location, homology, gene ontology, expression data, and more. Most sections are expanded by default, but you'll need to expand the \"homology\" section yourself.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g346083d4dc0_0_5.png){fig-align='center' fig-alt='To look at gene homology, you’ll need to expand the “homology” section yourself.' width=100%}\n:::\n:::\n\n\n\nOnce this section is expanded, you can find information about possible human homologs to the mouse gene, including alternate names and where the human homolog is located in the human genome.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g346083d4dc0_0_8.png){fig-align='center' fig-alt='You can find information about possible human homologs to the mouse gene, including alternate names and where the human homolog is located in the human genome.' width=100%}\n:::\n:::\n\n\n\nIf you continue scrolling down the page, you can also examine the pathways and processes the gene product is involved in under the \"gene ontology\" section. Clicking on the blue squares takes you to a page with more information about how that particular gene was assigned to a pathway or molecular process.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g346083d4dc0_0_11.png){fig-align='center' fig-alt='If you continue scrolling down the page, you can also examine the pathways and processes the gene product is involved in under the “gene ontology” section.' width=100%}\n:::\n:::\n\n\n\nDirectly underneath the \"ontology\" section is information about when the gene is expressed during development. You can learn more information by clicking on the blue squares, or by clicking on the links in the upper right-hand corner. These links will take you to other websites.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g346083d4dc0_0_18.png){fig-align='center' fig-alt='Directly underneath the “ontology” section is information about when the gene is expressed during development. You can learn more information by clicking on the blue squares, or by clicking on the links in the upper right-hand corner. These links will take you to other websites.' width=100%}\n:::\n:::\n\n\n\n### Looking up genes based on human gene name\n\nTODO: add instructions and screenshots for this - also add how to find the Ensembl geneID\n\n::: callout-note\nYou might come across some unexpected terms when you search the MGI for your gene ID. In addition to genes, Ensembl gene IDs are also given to \"pseudogenes\", \"putative genes\", and \"lncRNA\".\n\n**pseudogene**: This is a stretch of DNA that looks like a gene but doesn't actually code for any protein products. It's essentially a copy of a gene that contains mutations that prevent translation into a protein product. The mutations can include partial deletions, missing promoters, missing start codons, premature stop codons, frameshift mutations, or missing introns. Any of these are enough to result in a pseudogene.\n\n**putative gene**: This is a DNA segment that is believed to be a gene, but its function and protein product has not been confirmed. They are frequently identified based on the presence of an Open Reading Frame. Putative genes are not given names until they become confirmed genes.\n\n**lncRNA**: This stands for \"long non-coding RNA\". lncRNA is a type of RNA molecule that is transcribed from DNA but does not code for proteins. These RNA molecules are at least 200-500 nucleotides long and play roles in various biological processes, like gene regulation.\n:::\n\nOn the new page that you open, details about the gene are organized into familiar categories. Down the left-hand side of the page, you will see sections about the chromosomal location, homology, gene ontology, expression data, and more. Most sections are expanded by default, but you'll need to expand the \"homology\" section yourself.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g346083d4dc0_0_5.png){fig-align='center' fig-alt='To look at gene homology, you’ll need to expand the “homology” section yourself.' width=100%}\n:::\n:::\n\n\n\nOnce this section is expanded, you can find information about possible human homologs to the mouse gene, including alternate names and where the human homolog is located in the human genome.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g346083d4dc0_0_8.png){fig-align='center' fig-alt='You can find information about possible human homologs to the mouse gene, including alternate names and where the human homolog is located in the human genome.' width=100%}\n:::\n:::\n\n\n\nIf you continue scrolling down the page, you can also examine the pathways and processes the gene product is involved in under the \"gene ontology\" section. Clicking on the blue squares takes you to a page with more information about how that particular gene was assigned to a pathway or molecular process.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g346083d4dc0_0_11.png){fig-align='center' fig-alt='If you continue scrolling down the page, you can also examine the pathways and processes the gene product is involved in under the “gene ontology” section.' width=100%}\n:::\n:::\n\n\n\nDirectly underneath the \"ontology\" section is information about when the gene is expressed during development. You can learn more information by clicking on the blue squares, or by clicking on the links in the upper right-hand corner. These links will take you to other websites.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g346083d4dc0_0_18.png){fig-align='center' fig-alt='Directly underneath the “ontology” section is information about when the gene is expressed during development. You can learn more information by clicking on the blue squares, or by clicking on the links in the upper right-hand corner. These links will take you to other websites.' width=100%}\n:::\n:::\n\n\n\n\n### Looking up genes associated with a human disease\nTODO: add details and screenshots!\n\n## Analysis\n\nNow that you have your genes of interest, you're ready to start working with the dataset. \n\n### Package Install and Load\n\nWe will need to install the `tidyverse` package for this activity.\n\nType the following into the SciServer console and press return to run the code.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"tidyverse\")\n```\n:::\n\n\n\nNext, we will load the package so it's ready to use:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n\n::: callout-note\n\nPackages are collections of R code, data, and documentation that extend the base functionality of R. Think of them like \"expansion packs\" on top of your basic R software.\n\nPackages are developed by the R community and made available through repositories like CRAN (Comprehensive R Archive Network), Bioconductor, and GitHub. They are especially useful if you want to do a specialized kind of analysis, such as genomic analysis!\n\nWe use the `library` command to load and attach packages to the R environment. This means links the package you downloaded to your current session of R.\n\nThe \"tidyverse\" package that you loaded is useful for loading, wrangling, and exploring data.\n:::\n\n### Exploring the gene expression count data\n\nLet's start by looking at a dataset that includes information on how many times each gene was expressed in a sample. This is the gene expression count dataset.\n\nThis dataset gives us an idea of the scale of gene expression  - for example, which genes are expressed the most? Which genes are expressed the least? This is particularly useful when you want to know if a gene is usually turned on or off in a sample.\n\n#### Loading the gene expression count data\n\nYou can load this dataset into R using the following code:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngutbrain_genes <- read_csv(\"https://genomicseducation.org/data/mouse_gutbrain_de_counts.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 55421 Columns: 140\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr   (1): GeneID\ndbl (139): SRR6652436, SRR6652443, SRR6652469, SRR6652471, SRR6652505, SRR66...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\nThis dataset has 140 columns. Each row represents a gene. Each column is an individual mouse (sample), except for the first column (\"GeneID\", which is the Ensembl gene IDs) and the last column (\"total_counts\", which is the sum across all mice). \n\n#### Exploring and summarizing count data\n\nWhen you first open the gene expression data, you want to verify that the data has loaded correctly. You can do this with the `head` and `tail` commands. Remember, `head` prints the first 6 rows of a dataset, while `tail` prints the last 6 rows.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(gutbrain_genes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 140\n  GeneID       SRR6652436 SRR6652443 SRR6652469 SRR6652471 SRR6652505 SRR6652506\n  <chr>             <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>\n1 ENSMUSG0000…          0          0          0          0          0          0\n2 ENSMUSG0000…          0          0          0          0          0          0\n3 ENSMUSG0000…          0          0          0          0          0          0\n4 ENSMUSG0000…          0          0          0          0          0          0\n5 ENSMUSG0000…          0          0          0          0          0          0\n6 ENSMUSG0000…          0          0          0          0          0          0\n# ℹ 133 more variables: SRR6652507 <dbl>, SRR6652508 <dbl>, SRR6652509 <dbl>,\n#   SRR6652510 <dbl>, SRR6652511 <dbl>, SRR6652512 <dbl>, SRR6652513 <dbl>,\n#   SRR6652514 <dbl>, SRR6652515 <dbl>, SRR6652521 <dbl>, SRR6652522 <dbl>,\n#   SRR6652389 <dbl>, SRR6652390 <dbl>, SRR6652391 <dbl>, SRR6652392 <dbl>,\n#   SRR6652393 <dbl>, SRR6652394 <dbl>, SRR6652395 <dbl>, SRR6652396 <dbl>,\n#   SRR6652397 <dbl>, SRR6652398 <dbl>, SRR6652399 <dbl>, SRR6652400 <dbl>,\n#   SRR6652401 <dbl>, SRR6652402 <dbl>, SRR6652403 <dbl>, SRR6652404 <dbl>, …\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(gutbrain_genes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 140\n  GeneID       SRR6652436 SRR6652443 SRR6652469 SRR6652471 SRR6652505 SRR6652506\n  <chr>             <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>\n1 ENSMUSG0000…          0          0          0          0          0          0\n2 ENSMUSG0000…      18605      12561      14910      17809       6377      14750\n3 ENSMUSG0000…       4469       2944       3748       5384       2409       7057\n4 ENSMUSG0000…     117349      27498      68321      62645      65449     126271\n5 ENSMUSG0000…        175         36         87        100        148         18\n6 ENSMUSG0000…       3478        775       2437       1510       1665       5238\n# ℹ 133 more variables: SRR6652507 <dbl>, SRR6652508 <dbl>, SRR6652509 <dbl>,\n#   SRR6652510 <dbl>, SRR6652511 <dbl>, SRR6652512 <dbl>, SRR6652513 <dbl>,\n#   SRR6652514 <dbl>, SRR6652515 <dbl>, SRR6652521 <dbl>, SRR6652522 <dbl>,\n#   SRR6652389 <dbl>, SRR6652390 <dbl>, SRR6652391 <dbl>, SRR6652392 <dbl>,\n#   SRR6652393 <dbl>, SRR6652394 <dbl>, SRR6652395 <dbl>, SRR6652396 <dbl>,\n#   SRR6652397 <dbl>, SRR6652398 <dbl>, SRR6652399 <dbl>, SRR6652400 <dbl>,\n#   SRR6652401 <dbl>, SRR6652402 <dbl>, SRR6652403 <dbl>, SRR6652404 <dbl>, …\n```\n\n\n:::\n:::\n\n\n\nYou may want to explore the distribution of your count data using `summary`. This command lets you see the mean, median, minimum, and maximum for each numeric column. You can specify which column you'd like to get summary data for, or look at summary data for all the columns.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(gutbrain_genes$total_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.000e+00 9.600e+01 6.666e+03 4.130e+06 7.888e+05 7.732e+09 \n```\n\n\n:::\n:::\n\n\n\nYou can also find the total number of reads in the dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(gutbrain_genes$total_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.28913e+11\n```\n\n\n:::\n:::\n\n\n\n#### Plotting histograms and dealing with zero counts\n\nA histogram is a good way to visually explore the distribution of the read counts, as well as get an idea of how many genes have few or no reads. Use a log10 scale on the x-axis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(log10(gutbrain_genes$total_counts), main=\"Log10 Read Counts for Mouse RNA-seq sample\")\n```\n\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\nYou may choose to deal with zero-count genes by adding 0.1 to each count before the log10 transformation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngutbrain_genes$total_counts_trans <- gutbrain_genes$total_counts + 0.1\n\nhist(log10(gutbrain_genes$total_counts_trans), main=\"Transformed Log10 Read Counts for Mouse RNA-seq sample\")\n```\n\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n#### Looking at read count for a single gene\n\nYou may want to look at the read count for a specific gene in your dataset. This can be done with the `filter` command. Let's look at the read counts for the Reg3a gene, across all mice. Remember, this is the gene we looked up earlier in the MGI database. The Ensembl gene ID is \"ENSMUSG00000079516\".\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(gutbrain_genes, GeneID == \"ENSMUSG00000079516\")\n```\n:::\n\n\n\n#### Visualize gene counts of multiple genes across groups\n\nWe can also look at the differential gene expression of a set of genes at once! This is usually done by creating a **heatmap**. In RNA-seq analyses, we usually put individual samples on the x-axis and normalized gene counts on the y-axis.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g33d40c657bf_0_4.png){fig-align='center' fig-alt='Example of a heatmap.' width=100%}\n:::\n:::\n\n\n\nWhen creating heatmaps, we want to work with a dataset that includes normalized gene expression data for each gene. We loaded a dataset like this above that we called `gutbrain_genes`. If you don't have an object in your environment called this, scroll back up to the \"**Loading the gene expression count data**\" section and run the code again.\n\nThe dataset you loaded has expression data for 55,421 different genes, which is too many to visualize. (You can try, but R will usually throw an error if you do.) In general, though, we are mostly interested in looking at the visualization of a particular group of genes, or a gene set. \n\nLet's say we have identified 6 mouse genes that have been linked to the development of motor neurons. We're interested in whether these genes show differential gene expression between the striatum and the prefrontal cortex. We can use the `filter` command to pull out normalized gene expression data for just these six genes.\n\nThese are the genes (with gene IDs) that we're including in our gene set:\n\nSema3a: ENSMUSG00000028883\nMapk8: ENSMUSG00000021936\nNrcam: ENSMUSG00000020598\nDlg4: ENSMUSG00000020886\nSlit1: ENSMUSG00000025020\nCreb1: ENSMUSG00000025958\n\nFirst, create a vector that contains these gene IDs. (You can replace the gene IDs with the ones for your genes of interest, but make sure you use Ensembl gene IDs! They should all start with \"ENSMUSG\".)\n\nEach gene ID should have quotation marks around it, and the different IDs should be separated using a comma.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_set <- c(\"ENSMUSG00000028883\", \"ENSMUSG00000021936\", \"ENSMUSG00000020598\", \"ENSMUSG00000020886\", \"ENSMUSG00000025020\", \"ENSMUSG00000025958\")\n```\n:::\n\n\n\nNow we simply filter the `gutbrain_genes` dataset so that we only keep the rows for the gene IDs in our gene set. Remember, we want to use the `filter` command. The combination of `filter` and %in%` tells R to only keep those rows in the `gutbrain_genes` dataset if the gene ID is also found in our gene list we made earlier.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngutbrain_motor <- filter(gutbrain_genes, gutbrain_genes$GeneID %in% gene_set)\n\nhead(gutbrain_motor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 141\n  GeneID       SRR6652436 SRR6652443 SRR6652469 SRR6652471 SRR6652505 SRR6652506\n  <chr>             <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>\n1 ENSMUSG0000…      86704      93818      62879     116582      50148      93087\n2 ENSMUSG0000…    2220069    1537477    1521896    1355721     945194    1790682\n3 ENSMUSG0000…     462615     362226     557979     714703     396624     750340\n4 ENSMUSG0000…     113380     104242     156926     223405     111427     211342\n5 ENSMUSG0000…      26284      19265      74037      56337      49613      93139\n6 ENSMUSG0000…      44034      30884      26225      45861      26901      46580\n# ℹ 134 more variables: SRR6652507 <dbl>, SRR6652508 <dbl>, SRR6652509 <dbl>,\n#   SRR6652510 <dbl>, SRR6652511 <dbl>, SRR6652512 <dbl>, SRR6652513 <dbl>,\n#   SRR6652514 <dbl>, SRR6652515 <dbl>, SRR6652521 <dbl>, SRR6652522 <dbl>,\n#   SRR6652389 <dbl>, SRR6652390 <dbl>, SRR6652391 <dbl>, SRR6652392 <dbl>,\n#   SRR6652393 <dbl>, SRR6652394 <dbl>, SRR6652395 <dbl>, SRR6652396 <dbl>,\n#   SRR6652397 <dbl>, SRR6652398 <dbl>, SRR6652399 <dbl>, SRR6652400 <dbl>,\n#   SRR6652401 <dbl>, SRR6652402 <dbl>, SRR6652403 <dbl>, SRR6652404 <dbl>, …\n```\n\n\n:::\n:::\n\n\n \nwe're not quite ready to make our heatmap yet. Because we are interested in the gene expression of these six genes in the striatum compared to the prefrontal cortex, we want to control for any possible differences caused by the sample coming from an ASD-type mouse vs a control-type mouse. So we also want to select a subset of the samples so that we're only using those samples from control-type mice.\n\nTODO: actually create heatmap\n\n\n### Exploring the differential expression data\n\nNow let's look a differential expression dataset, which compares gene expression counts between two groups. This dataset gives us an idea how the change in a gene's expression might be associated with a disorder or a cell type. This is particularly useful for beginning to map the genetic drivers of a particular phenotype.\n\n#### Loading the differential expression data\n\nLet's say you want to open the dataset that compares gene expression between ASD and control mice in both brain regions and call it `asd_vs_c`. We will do this using `read_csv`. Copy and paste this command into your console:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c <- read_csv(\"https://genomicseducation.org/data/mouse_gutbrain_de_autismVcontrol.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 55421 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): gene\ndbl (6): baseMean, log2FoldChange, lfcSE, stat, pvalue, padj\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\nHere are the URLs for all the possible comparisons you can examine with this dataset:\n\n**Comparing gene expression between ASD and control mice**\n\nBoth brain regions: <https://genomicseducation.org/data/mouse_gutbrain_de_autismVcontrol.csv>\n\nPrefrontal cortex only: <https://genomicseducation.org/data/mouse_gutbrain_de_autismVcontrol_in_prefrontalcortex.csv>\n\nStriatum only: <https://genomicseducation.org/data/mouse_gutbrain_de_autismVcontrol_in_striatum.csv>\n\n**Comparing gene expression between prefrontal cortex and striatum**\n\nAll mice: <https://genomicseducation.org/data/mouse_gutbrain_de_tissuetype.csv>\n\nOnly ASD mice: <https://genomicseducation.org/data/mouse_gutbrain_de_tissuetype_in_ASDmice.csv>\n\nOnly control mice: <https://genomicseducation.org/data/mouse_gutbrain_de_tissuetype_in_controlmice.csv>\n\n::: callout-tip\n# Which differential expression dataset should I use?\n\nEven though this dataset is from a single study, there are still lots of options for independent research questions. You have the option to look at gene expression in control-type vs ASD-type mice, as well as gene expression in both striatum and prefrontal cortex. All the mice were male and sacrificed at the same age (45 days).\n\nAdditionally, you can look at gene expression in striatum vs prefrontal cortex in only ASD-type mice or only control-type mice. Likewise, you also have the option of looking at gene expression in ASD and control mice, focusing only on striatum or only on prefrontal cortex.\n\nAre you mostly interested in how gene expression differs between the two brain regions? Are you interested in how neurons develop, or how groups of genes involved in movement might be expressed differently in two different regions? These sorts of questions are best to explore using **striatum and prefrontal cortex** comparisons.\n\nAre you really curious about differential expression in Autism Spectrum Disorder-type mice compared to control-type mice? Are you curious about potential associations between gene expression differences in known neurodevelopmental genes? These questions and others can be explored using the **ASD-type mice and control-type mice** comparisons.\n:::\n\n#### Ranking the genes by log2FoldChange\n\nThe `log2FoldChange` value gives us an idea of which genes show the greatest differential expression between the ASD mice and the control mice. It is a log-transformed ratio of how many gene transcripts were found in ASD-type mice compared to control-type mice. We take the log2 of this ratio (the fold change) because it makes interpretation easier. Genes with no difference in expression between groups have `log2FoldChange` values close to zero. Negative log2FoldChange values means a **decreased expression** (or, a downregulation in gene expression) in the experimental group versus the control group. Positive log2FoldChange values indicate genes that are upregulated, or have **increased expression** in the experimental group versus the control group.\n\nWe can arrange the table based on these values (going from smallest to largest) by copying the following code into your console:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c_ascending <- arrange(asd_vs_c, log2FoldChange)\nhead(asd_vs_c_ascending)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  gene               baseMean log2FoldChange lfcSE  stat   pvalue     padj\n  <chr>                 <dbl>          <dbl> <dbl> <dbl>    <dbl>    <dbl>\n1 ENSMUSG00000089657     16.9          -25.5  1.81 -14.1 2.18e-45 7.29e-41\n2 ENSMUSG00000102414     14.9          -25.4  1.89 -13.4 4.00e-41 3.81e-37\n3 ENSMUSG00000083812     14.6          -25.4  1.80 -14.1 3.82e-45 7.29e-41\n4 ENSMUSG00000074445     11.5          -25.0  1.89 -13.3 3.44e-40 2.62e-36\n5 ENSMUSG00000094151     11.2          -25.0  1.79 -14.0 2.97e-44 3.77e-40\n6 ENSMUSG00000053773     10.6          -24.9  1.99 -12.5 6.66e-36 4.23e-32\n```\n\n\n:::\n:::\n\n\n\nThe genes at the top of this table have the most negative log2FoldChange values and are downregulated in ASD-type mice. \n\nWe can use a similar command to look at the genes with the largest positive log2FoldChange. These are genes that are upregulated in ASD-type mice.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c_descending <- arrange(asd_vs_c, desc(log2FoldChange))\nhead(asd_vs_c_descending)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  gene               baseMean log2FoldChange lfcSE  stat   pvalue     padj\n  <chr>                 <dbl>          <dbl> <dbl> <dbl>    <dbl>    <dbl>\n1 ENSMUSG00000102375     7.19          24.1   2.29 10.5  6.88e-26 2.91e-22\n2 ENSMUSG00000104583     5.77          24.0   2.31 10.4  2.48e-25 9.47e-22\n3 ENSMUSG00000042414     6.81           6.42  2.93  2.19 2.85e- 2 1.00e+ 0\n4 ENSMUSG00000048763     6.33           6.32  2.30  2.75 6.04e- 3 1.00e+ 0\n5 ENSMUSG00000117911     5.18           6.03  2.77  2.18 2.93e- 2 1.00e+ 0\n6 ENSMUSG00000085421     4.74           5.90  2.93  2.01 4.42e- 2 1.00e+ 0\n```\n\n\n:::\n:::\n\n\n\nWhen we're interpreting the `log2FoldChange`, remember that you'll need to do a little bit of math. A `log2FoldChange` value of 1 is a fold change value of 2 (2^1 = 2). Similarly, a `log2FoldChange` value of 4 is a fold change value of 8 (2^4 = 8)\n\nIf there is a two fold **increase** (fold change = 2, `log2FoldChange` = 1) between groups A and B, then the expression in group A is twice as big as the expression in group B.\n\nIf there is a two fold **decrease** (fold change = 0.5, `log2FoldChange` = -1) between groups A and B, then the expression in group A is half as big as the expression in group B (or B is twice as big as A).\n\n#### Arranging dataset based on padj\n\nMaybe you also want to arrange the genes by whether the estimated differential expression is significant. Instead of `log2FoldChange`, you will want to look at `padj`. You can use the `arrange` command to sort the results to put the smallest padj values first.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c_sorted <- arrange(asd_vs_c, padj)\nhead(asd_vs_c_sorted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  gene               baseMean log2FoldChange lfcSE  stat   pvalue     padj\n  <chr>                 <dbl>          <dbl> <dbl> <dbl>    <dbl>    <dbl>\n1 ENSMUSG00000089657     16.9          -25.5  1.81 -14.1 2.18e-45 7.29e-41\n2 ENSMUSG00000083812     14.6          -25.4  1.80 -14.1 3.82e-45 7.29e-41\n3 ENSMUSG00000094151     11.2          -25.0  1.79 -14.0 2.97e-44 3.77e-40\n4 ENSMUSG00000102414     14.9          -25.4  1.89 -13.4 4.00e-41 3.81e-37\n5 ENSMUSG00000074445     11.5          -25.0  1.89 -13.3 3.44e-40 2.62e-36\n6 ENSMUSG00000053773     10.6          -24.9  1.99 -12.5 6.66e-36 4.23e-32\n```\n\n\n:::\n:::\n\n\n\n#### Compare differential gene expression of a single across groups\n\nIt might be interesting to look at the expression of a gene across our two brain regions. To do this, we will first load the region-specific datasets.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c_prefrontal <- read_csv(\"https://genomicseducation.org/data/mouse_gutbrain_de_autismVcontrol_in_prefrontalcortex.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 55421 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): gene\ndbl (6): baseMean, log2FoldChange, lfcSE, stat, pvalue, padj\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nasd_vs_c_striatum <- read_csv(\"https://genomicseducation.org/data/mouse_gutbrain_de_autismVcontrol_in_striatum.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 55421 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): gene\ndbl (6): baseMean, log2FoldChange, lfcSE, stat, pvalue, padj\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\nThen we'll filter out the gene in which we're interested from each object. Let's take a look at gene ENSMUSG00000079516, which is the Reg3a gene we previously looked up on MGI.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg3a_prefrontal <- filter(asd_vs_c_prefrontal, gene == \"ENSMUSG00000079516\")\n\nreg3a_striatum <- filter(asd_vs_c_striatum, gene == \"ENSMUSG00000079516\")\n```\n:::\n\n\n\nFinally, take a look at the differential expression of reg3a in each region.\n\nIn the prefrontal cortex:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg3a_prefrontal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  gene               baseMean log2FoldChange lfcSE  stat   pvalue     padj\n  <chr>                 <dbl>          <dbl> <dbl> <dbl>    <dbl>    <dbl>\n1 ENSMUSG00000079516     10.6          -22.6  2.11 -10.7 7.30e-27 2.63e-23\n```\n\n\n:::\n:::\n\n\n\nIn the striatum:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg3a_striatum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  gene               baseMean log2FoldChange lfcSE  stat pvalue  padj\n  <chr>                 <dbl>          <dbl> <dbl> <dbl>  <dbl> <dbl>\n1 ENSMUSG00000079516    0.371           2.27  2.96 0.765  0.444    NA\n```\n\n\n:::\n:::\n\n\n\n\n#### Creating a volcano plot to visualize differential expression of multiple genes\n\nA volcano plot is a great way to visualize differential gene expression between two datasets. These types of plots have `log2FoldChange` on the x-axis and a log transformed `padj` on the y-axis.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html//1vikcyml6uw-_DaC1yFpS-UWoWNEGxFukMB_eCi42BqY_g36a8fbcc346_0_0.png){fig-align='center' fig-alt='Example of a volcano plot.' width=100%}\n:::\n:::\n\n\n\nWe will first need to do a log transformation of the `padj` variable. We do this in order to spread our values out along the y-axis - otherwise, all the dots that represent genes will be too scrunched together.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c$padj_trans <- -log10(asd_vs_c$padj)\n```\n:::\n\n\n\nNow, we just create a scatterplot. The code for this is kind of complicated, so you will want to paste the code below into your console.\n\nHere's the code for your basic volcano plot. `data` tells R what data to use, `x` tells R what the x-axis values should be, and `y` tells R what the y-axis values should be. Notice that we can just use the column names for `x` and `y`!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = asd_vs_c, aes(x = log2FoldChange, y = padj_trans)) +\n         geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 17318 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n\nWe can also color code the genes (points) which are significantly upregulated or downregulated. In order to do this, we will need to create a new column in our dataset that identifies whether a gene is upregulated in ASD-type mice, downregulated in ASD-type mice, or has the same regulation in ASD-type mice compared to control-type mice.\n\nIn this new column, we can decide the thresholds that a `log2FoldChange` value must meet in order to be considered upregulated or downregulated. We will consider genes to be upregulated if the log2fold change is greater than 0.6 and downregulated if it is less than -0.6. **You can change these thresholds to whatever makes sense for you.** \n\n::: {tip}\nlog2foldchange is just a representation of a ratio, so the sign indicates the direction of regulation. It's important to remember which group is your comparison group! \n\nFor example, if you are look at regulation in group A compared to group B, you might have a log2foldchange value of 1 (indicating the gene is expressed twice as much in A as it is in B).\n\nHowever, if you are looking at regulation in group B compared to group A, the log2foldchange value will be -1 (because the gene is expressed half as much in B as it is in A).\n\nThe comparison group matters with ratios!\n:::\n\nWe are also setting a significant p-value as less than 0.05 (but you can also change this based on your best judgment).\n\nWe start by creating a new column called `diffexpressed` and setting everything to \"NO\" (as in \"no expression differences between ASD-type and control-type mice\"). We then specify the genes for which this column should be changed to \"UP\" or \"DOWN\" (based on `log2FoldChange` and `padj`).\n\nTo recap:\nA gene is labeled \"UP\" if its log2FoldChange value is greater than 0.6 _and_ its adjusted p-value is less than 0.05.\n\nA gene is labeled \"DOWN\" if its log2FoldChange value is less than -0.6 _and_ its adjusted p-value is less than 0.05.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c$diffexpressed <- \"NO\"\n\nasd_vs_c$diffexpressed[asd_vs_c$log2FoldChange > 0.6 & asd_vs_c$padj < 0.05] <- \"UP\"\n\nasd_vs_c$diffexpressed[asd_vs_c$log2FoldChange < -0.6 & asd_vs_c$padj < 0.05] <- \"DOWN\"\n\nhead(asd_vs_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  gene          baseMean log2FoldChange lfcSE  stat   pvalue     padj padj_trans\n  <chr>            <dbl>          <dbl> <dbl> <dbl>    <dbl>    <dbl>      <dbl>\n1 ENSMUSG00000…     16.9          -25.5  1.81 -14.1 2.18e-45 7.29e-41       40.1\n2 ENSMUSG00000…     14.6          -25.4  1.80 -14.1 3.82e-45 7.29e-41       40.1\n3 ENSMUSG00000…     11.2          -25.0  1.79 -14.0 2.97e-44 3.77e-40       39.4\n4 ENSMUSG00000…     14.9          -25.4  1.89 -13.4 4.00e-41 3.81e-37       36.4\n5 ENSMUSG00000…     11.5          -25.0  1.89 -13.3 3.44e-40 2.62e-36       35.6\n6 ENSMUSG00000…     10.6          -24.9  1.99 -12.5 6.66e-36 4.23e-32       31.4\n# ℹ 1 more variable: diffexpressed <chr>\n```\n\n\n:::\n:::\n\n\n\nOkay! We can now add some color to the volcano plot we made earlier. We do this by adding a line to our code that tells R to color the data points based on the `diffexpressed` column (`col = diffexpressed`). We also add a line about the colors we want to use (`scale_color_manual`). In this case, we have chosen to make the points for downregulated genes turquoise and the points for upregulated genes gold. The additional command `labels` just creates the labels on the legend.\n\nYou can find an extensive list of all the colors available in R at [https://www.datanovia.com/en/blog/awesome-list-of-657-r-color-names/](https://www.datanovia.com/en/blog/awesome-list-of-657-r-color-names/).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = asd_vs_c, aes(x = log2FoldChange, y = padj_trans, col = diffexpressed)) +\n  geom_point() +\n  scale_color_manual(values = c(\"turquoise\", \"grey\", \"gold\"), \n  labels = c(\"Downregulated\", \"Not significant\", \"Upregulated\")) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 17318 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n\nWe can also label genes of interest in our plot. Let's label the Reg3a gene (the same one we looked up in the MGI database), as well as Pcdh12 (or protocadherin 12). The two gene IDs we need to know are ENSMUSG00000079516 and ENSMUSG00000024440.\n\nWe will create another new column in our dataset. We will then tell R  In this new column, the genes in our list (Reg3a and Pcdh12) are named, which everything else will have a missing name. When we remake the volcano plot, R will _only_ label those points that do not have missing names in the `gene_label` column.\n\nThis is going to require a little bit of R trickery and something called a \"case_when\" statement.\n\nIn R, an \"case_when\" statement tells R to do something only when a condition is true. In our command, R is going through the `asd_vs_c` row by row. For each row, we are telling R to first check whether the geneID of that row is \"ENSMUSG00000079516\". If it is, then R will fill in the `gene_label` column with the gene symbol \"Reg3a\". If it is not, R moves onto the next part of our command.\n\nWhen R moves onto this second command, it's now checking to see if the geneID for the row is \"ENSMUSG00000024440\". If it is, then R fills in the `gene_label` column with the gene symbol \"Pcdh12\". If it is not, R moves to the third command in the `case_when` statement. The final line tells R to fill in the `gene_label` column with \"NA\" for any row that didn't match the previous commands. This will tell R in the future that the information for this column is missing.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c$gene_label <- case_when(\n  asd_vs_c$gene == \"ENSMUSG00000079516\" ~ \"Reg3a\",\n  asd_vs_c$gene == \"ENSMUSG00000024440\" ~ \"Pcdh12\",\n  TRUE ~ NA_character_\n)\n```\n:::\n\n\n\nGreat! You can check to see what the new column `gene_label` looks like by using the `head` command.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(asd_vs_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 10\n  gene          baseMean log2FoldChange lfcSE  stat   pvalue     padj padj_trans\n  <chr>            <dbl>          <dbl> <dbl> <dbl>    <dbl>    <dbl>      <dbl>\n1 ENSMUSG00000…     16.9          -25.5  1.81 -14.1 2.18e-45 7.29e-41       40.1\n2 ENSMUSG00000…     14.6          -25.4  1.80 -14.1 3.82e-45 7.29e-41       40.1\n3 ENSMUSG00000…     11.2          -25.0  1.79 -14.0 2.97e-44 3.77e-40       39.4\n4 ENSMUSG00000…     14.9          -25.4  1.89 -13.4 4.00e-41 3.81e-37       36.4\n5 ENSMUSG00000…     11.5          -25.0  1.89 -13.3 3.44e-40 2.62e-36       35.6\n6 ENSMUSG00000…     10.6          -24.9  1.99 -12.5 6.66e-36 4.23e-32       31.4\n# ℹ 2 more variables: diffexpressed <chr>, gene_label <chr>\n```\n\n\n:::\n:::\n\n\n\nNow we just need to remake our volcano plot and add some to code that tells R to label the points we're interested in. The command `label = gene_label` goes right after the code that tells R how to color the points. We also need to add something at the end of our code that tells R to put the labels on top of the plot that we've made. That's the `+\n  geom_text_repel(max.overlaps = Inf)` command.\n  \nIn order for this command to work, we do need to install and load a new library called `ggrepel`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages('ggrepel')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nInstalling package into '/usr/local/lib/R/site-library'\n(as 'lib' is unspecified)\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggrepel)\n```\n:::\n\n\n\nExcellent. Now that we have installed and loaded this package (which you only need to do once for each R session!), we can run the code to create the volcano plot. Remember, we added `label = gene_label` to tell R to add labels to the points, and `geom_text_repel(max.overlaps = Inf)` to tell R to put the labels on top of the plot so we can see them.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = asd_vs_c, aes(x = log2FoldChange, y = padj_trans, col = diffexpressed, label = gene_label)) +\n  geom_point() +\n  scale_color_manual(values = c(\"turquoise\", \"grey\", \"gold\"), \n  labels = c(\"Downregulated\", \"Not significant\", \"Upregulated\")) +\n  geom_text_repel(max.overlaps = Inf)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 17318 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 55419 rows containing missing values or values outside the scale range\n(`geom_text_repel()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n\nYou may want to add a title to your plot. This can be done  with the `ggtitle` command.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = asd_vs_c, aes(x = log2FoldChange, y = padj_trans, col = diffexpressed, label = gene_label)) +\n  geom_point() +\n  scale_color_manual(values = c(\"turquoise\", \"grey\", \"gold\"), \n  labels = c(\"Downregulated\", \"Not significant\", \"Upregulated\")) +\n  geom_text_repel(max.overlaps = Inf) +\n  ggtitle(\"Differential Expression in Mouse Prefrontal Cortex\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 17318 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 55419 rows containing missing values or values outside the scale range\n(`geom_text_repel()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n\nHere's all the code we used to build a volcano plot in one place so that you can easily run it again (and make modifications).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#log transform the padj values so the y-axis is formatted for plotting\nasd_vs_c$padj_trans <- -log10(asd_vs_c$padj)\n\n#Create the diffexpressed column so that we can color the upregulated and downregulated genes on the plot\nasd_vs_c$diffexpressed <- \"NO\"\n\nasd_vs_c$diffexpressed[asd_vs_c$log2FoldChange > 0.6 & asd_vs_c$padj < 0.05] <- \"UP\"\n\nasd_vs_c$diffexpressed[asd_vs_c$log2FoldChange < -0.6 & asd_vs_c$padj < 0.05] <- \"DOWN\"\n\n#Create the gene_label column so that we can label individual points\nasd_vs_c$gene_label <- case_when(\n  asd_vs_c$gene == \"ENSMUSG00000079516\" ~ \"Reg3a\",\n  asd_vs_c$gene == \"ENSMUSG00000024440\" ~ \"Pcdh12\",\n  TRUE ~ NA_character_\n)\n\n#Make the final plot\nggplot(data = asd_vs_c, aes(x = log2FoldChange, y = padj_trans, col = diffexpressed, label = gene_label)) +\n  geom_point() +\n  scale_color_manual(values = c(\"turquoise\", \"grey\", \"gold\"), \n  labels = c(\"Downregulated\", \"Not significant\", \"Upregulated\")) +\n  geom_text_repel(max.overlaps = Inf) +\n  ggtitle(\"Differential Expression in Mouse Prefrontal Cortex\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 17318 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 55419 rows containing missing values or values outside the scale range\n(`geom_text_repel()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](resources/images/mouse_gutbrain_de_independent_guide_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n\n#### Running a gene set analysis\n\nYou can use the special command `runClusterProfiler` to figure out the types of processes genes on your gene list are involved in. You can also create a dotplot to visualize your results. (NOTE: this is only possible if you are using the C-MOOR environment in SciServer.)\n\nYou created a gene list in the **Visualize gene counts of multiple genes across groups** section above. The code from this section is repeated below in case you need to run it again.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_set <- c(\"ENSMUSG00000028883\", \"ENSMUSG00000021936\", \"ENSMUSG00000020598\", \"ENSMUSG00000020886\", \"ENSMUSG00000025020\", \"ENSMUSG00000025958\")\n```\n:::\n\n\n\nThen we can create a subset of the `asd_vs_c` dataset by filtering out any genes that aren't on our gene list. Remember, we do this using `filter` and `%in%`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c_motor <- filter(asd_vs_c, asd_vs_c$gene %in% gene_set)\n```\n:::\n\n\n\nFinally, create your cluster profile with the `runClusterProfiler` and `dotplot` commands.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasd_vs_c_clusters <- runClusterProfiler(asd_vs_c_sig)\n\ndotplot(asd_vs_c_clusters, showCategory=34, title=\"asd vs control in prefrontal cortex\", font.size=10, label_format = 50)\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}